### ISSUE TITLE
CDN down

### ISSUE THREAD

**Issue by JesusOnTheKeys** [DoingFedTime/BreachForums#2]
I believe the cdn is down i cannot access it from several different Mullvad vpns could just be me but cloudflare thinks its server

**Comment by DisruptiveCollective** [comment]
same here from multiple IPs does seem to be down. 

Error downloading https://bncdn.to/breachnationcdn/8fit_BF.7z: 523 Server Error:  for url: https://bncdn.to/breachnationcdn/8fit_BF.7z
Downloading 8tracks_BF.7z...
Error downloading https://bncdn.to/breachnationcdn/8tracks_BF.7z: 523 Server Error:  for url: https://bncdn.to/breachnationcdn/8tracks_BF.7z
Downloading Facebook_BF.7z...
Error downloading https://bncdn.to/breachnationcdn/Facebook_BF.7z: 523 Server Error:  for url: https://bncdn.to/breachnationcdn/Facebook_BF.7z
Downloading LinkedIn_BF.7z...

**Comment by JesusOnTheKeys** [comment]
If @DoingFedTime needs a alternative domain they are hosted here https://river.bz/ albeit it has cloudflare so this tool will need to be updated to either using selenium or some sort of work around :)

**Comment by DoingFedTime** [comment]
Unfortunately, I do not host any of the files, nor do I own the CDN. 
If the data is no longer available then the tool is useless and as a result I will archive the project.
